<a href="https://colab.research.google.com/github/mp-codez/ai-linear-algebra/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[1, 3, 4],[6, 4, 1],[2, 2, 2]])
A

array([[1, 3, 4],
       [6, 4, 1],
       [2, 2, 2]])

In [4]:
B = np.array([5, 16, 11])
B

array([ 5, 16, 11])

In [6]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.75 , -0.25 ,  1.625],
       [ 1.25 ,  0.75 , -2.875],
       [-0.5  , -0.5  ,  1.75 ]])

In [7]:
x, y, z = np.dot(A_inv, B)

In [8]:
x

np.float64(10.125)

In [9]:
y

np.float64(-13.375)

In [10]:
z

np.float64(8.75)